### ISSUE TITLE
Page not showing any items

### ISSUE THREAD

**Issue by kridafar** [Mathlit/ChecklistPrime#1]
Not sure if I did something but I cant get any items to show up, I have been using this for a week or so and love it and am hoping this is still active....

**Comment by Mathlit** [comment]
While I'm not actively working on it anymore, I'm keeping it online and up to date. I'll see if I can find the issue!

**Comment by kridafar** [comment]
![image](https://user-images.githubusercontent.com/39853821/45929783-ffa10400-bf88-11e8-96ce-d8b84bd5b06c.png)
This is what it looks like now

**Comment by Mathlit** [comment]
Problem has been solved. The API runs on my own server and I forgot to renew the SSL certificates 😅
